import { ConstructorCallTransactionResponseModel } from "./ConstructorCallTransactionResponseModel";
import { StorageReferenceModel } from "../values/StorageReferenceModel";
import { UpdateModel } from "../updates/UpdateModel";
export declare class ConstructorCallTransactionSuccessfulResponseModel extends ConstructorCallTransactionResponseModel {
    /**
     * The events generated by this transaction.
     */
    events: Array<StorageReferenceModel>;
    /**
     * The object that has been created by the constructor call.
     */
    newObject: StorageReferenceModel;
    constructor(updates: Array<UpdateModel>, gasConsumedForCPU: string, gasConsumedForRAM: string, gasConsumedForStorage: string, events: Array<StorageReferenceModel>, newObject: StorageReferenceModel);
}
