import { Marshallable } from "../../marshalling/Marshallable";
import { TransactionReferenceModel } from "../values/TransactionReferenceModel";
export declare abstract class TransactionRequestModel extends Marshallable {
    /**
     * Yields the reference to the transaction generated by this request.
     * @param signature the signature of this request in base64
     * @return the transaction reference or null
     */
    getReference(signature: string): TransactionReferenceModel | null;
}
