import {ConstructorCallTransactionResponseModel} from "./ConstructorCallTransactionResponseModel";
import {StorageReferenceModel} from "../values/StorageReferenceModel";
import {UpdateModel} from "../updates/UpdateModel";

/**
 * A response for a successful transaction that calls a constructor of a storage
 * class in blockchain. The constructor has been called without problems and
 * without generating exceptions.
 */
export class ConstructorCallTransactionSuccessfulResponseModel extends ConstructorCallTransactionResponseModel {
    /**
     * The events generated by this transaction.
     */
    events: Array<StorageReferenceModel>

    /**
     * The object that has been created by the constructor call.
     */
    newObject: StorageReferenceModel


    constructor(
        updates: Array<UpdateModel>,
        gasConsumedForCPU: string,
        gasConsumedForRAM: string,
        gasConsumedForStorage: string,
        events: Array<StorageReferenceModel>,
        newObject: StorageReferenceModel
    ) {
        super(updates, gasConsumedForCPU, gasConsumedForRAM, gasConsumedForStorage)
        this.events = events
        this.newObject = newObject
    }
}